name: Release
on:
  pull_request:
    branches:
      - release-*
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: Which package to release
        options: 
          - "contracts"
          - "configs"

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} #reset

jobs:
  
  start:
    runs-on: ubuntu-latest
    name: Start Release Candidate
    ## Run this job only if Manually triggered by the user on UI of main branch.
    if: ${{ github.ref_name == 'main' && github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: bash scripts/git-user-config.sh
      - name: Create Release Candidate Branch
        id: start
        run: bash scripts/start.sh
        env:
          PACKAGE: ${{ github.event.inputs.package }}
      - name: Re-run workflow
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: repo,
              workflow_id: 'release-cycle.yml',
              ref: '${{ steps.start.outputs.branch }}',
            });
  
  changesets:
    runs-on: ubuntu-latest
    name: Update PR to release
    ## Run this: 
    ##  1. when we do `promote`, triggering_actor becomes bot in this case as we re-run the workflow.
    ##  2. If the push happens to `release-` branch, it should re-update the changeset PR.    
    if: |
      (
        contains(github.ref_name, 'release-') && 
        github.event_name == 'workflow_dispatch' &&  
        github.triggering_actor == 'github-actions[bot]'
      ) || 
      github.event_name == 'pull_request'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: bash scripts/git-user-config.sh
      - name: Create/Update PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn ignore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
          TRIGGERING_ACTOR: ${{ github.triggering_actor }}
    
  promote:
    runs-on: ubuntu-latest
    name: Promote to final release
    permissions:
      contents: write
      actions: write
    # Run this if we manually triggered a workflow on `release-` branch.
    if: | 
      (
        contains(github.ref_name, 'release-') && 
        github.event_name == 'workflow_dispatch' &&  
        github.triggering_actor != 'github-actions[bot]'
      )
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: bash scripts/git-user-config.sh
      - name: Exit prerelease state
        run: bash scripts/exit-prerelease.sh
      - name: Re-run workflow
        uses: actions/github-script@v7
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: repo,
              workflow_id: 'release-cycle.yml',
              ref: 'release-configs'
            });
  
  # publish:
  #   runs-on: ubuntu-latest
  #   name: Publish to npm and create a release/tag
  #   if: | 
  #     (
  #       contains(github.ref_name, 'release-') && 
  #       github.event_name == 'push' &&  
  #       github.triggering_actor != 'github-actions[bot]'
  #     )
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #     - run: yarn install
  #     - run: bash scripts/git-user-config.sh
  #     - run: echo ${{ github.ref_name }}
  #     - name: Create temporary .npmrc
  #       run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
  #     - name: Publish to npm
  #       uses: actions/github-script@v7
  #       env:
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         script: await require('./scripts/publish.js')({ github, context })